feat: added list theme function

diff --git a/usr/lib/theme-switch/core b/usr/lib/theme-switch/core
--- a/usr/lib/theme-switch/core
+++ b/usr/lib/theme-switch/core
@@ -28,6 +28,35 @@ checkUserConfig() {
 	done
 }
 
+listThemes() {
+	local program="$1"
+	local theme_dir
+	local extension
+
+	case "$program" in
+	vim | nvim)
+		theme_dir="$VIM_THEME_DIR"
+		extension=".vim"
+		;;
+	kitty)
+		theme_dir="$KITTY_THEME_DIR"
+		extension=".conf"
+		;;
+	*)
+		echo "Error: Unsupported program '$program'. Use 'vim', 'nvim', or 'kitty'."
+		exit 1
+		;;
+	esac
+
+	if [ ! -d "$theme_dir" ]; then
+		echo "Error: Theme directory '$theme_dir' not found."
+		exit 1
+	fi
+
+	# List themes, remove extensions, format into one line, wrap text, and show in less
+	find "$theme_dir" -type f -name "*$extension" -printf "%f\n" | sed "s/$extension$//" | paste -sd " " - | fold -s | less -R
+}
+
 loadConfig() {
 	if [ -f "$THEME_CONFIG_FILE" ]; then
 		source "$THEME_CONFIG_FILE"
@@ -56,7 +85,7 @@ showDetails() {
 
 setTheme() {
 	local theme_type="$1"
-  local action="$2"
+	local action="$2"
 
 	if [ "$theme_type" = "dark" ]; then
 		NVIM_TEMPLATE="$NVIM_DARK_TEMPLATE"
@@ -99,7 +128,7 @@ toggleTheme() {
 
 	# Proceed to toggle the theme if all checks passed
 	if [ "$current_theme" = "dark" ]; then
-		setTheme "light" "Switched to" 
+		setTheme "light" "Switched to"
 	else
 		setTheme "dark" "Switched to"
 	fi
@@ -175,8 +204,8 @@ setOpacity() {
 }
 
 printHelp() {
-  script_name=$(basename "$0")
-  echo "Usage: $script_name [option]"
+	script_name=$(basename "$0")
+	echo "Usage: $script_name [option]"
 	echo "Options:"
 	echo "  -v, --version                              Show the version number"
 	echo "  -t, --toggle                               Toggle between dark and light themes"
